projet_index:
    path: /projet
    defaults: { _controller: "AppBundle:Projet:index" }
    methods:  ['GET']

projet_new:
    path: /projet/new
    defaults: { _controller: "AppBundle:Projet:new" }
    methods:  ['GET','POST']

projet_show:
    path: /projet/{idProjet}
    defaults: { _controller: "AppBundle:Projet:show" }
    methods:  ['GET']

projet_edit:
    path: /projet/edit/{idProjet}
    defaults: { _controller: "AppBundle:Projet:edit" }
    methods:  ['GET','POST']

projet_delete:
    path: /projet/{idProjet}
    defaults: { _controller: "AppBundle:Projet:delete" }
    methods:  ['DELETE']