# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
       # user_provider:
        #     id: app.user_provider


        ticketv_provider:
            entity:
                class: AppBundle:User
                #property: username #si on decommente cette property on a un autre comportement et ça ne passe pas par le repository

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                 authenticators:
                     - app.form_login_authenticator
            form_login:
                login_path: login
                check_path: login_check
                username_parameter: username_ticketv
                password_parameter: password
                always_use_default_target_path: true
                default_target_path: ticket_index
            # activate different ways to authenticate
           # provider: user_provider
            provider: ticketv_provider
            # http_basic: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }