# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html

services:
    app.form_login_authenticator:
        class: AppBundle\Security\FormLoginAuthenticator
        arguments:
        - "@security.password_encoder"
        - "@router"

