<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Ticket;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllByUtilisateur($id_utilisateur,$actif=true)
    {

       return $this->getEntityManager()
                     ->createQuery( 'SELECT t FROM AppBundle:Ticket t, AppBundle:SuiviTicket st, AppBundle:Statut s
                                                    WHERE t.idTicket = st.idTicket
                                                    AND t.idStatut = s.idStatut'.($actif?' AND s.clos = 0':'').'
                                                    AND st.idUtilisateur = '.$id_utilisateur.'
                                                    AND st.idSuiviTicket = (SELECT MAX(st2.idSuiviTicket) FROM AppBundle:SuiviTicket st2 WHERE st2.idTicket = t.idTicket)')
                     ->getResult();
    }
}