<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CommentaireTicket;
use AppBundle\Entity\FosUser;
use AppBundle\Entity\Ticket;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
/**
 * CommentaireTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuiviTicketRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllByTicket($id_ticket)
    {

        return $this->createQueryBuilder('s')
                            ->where('s.idTicket = :id_ticket')
                            ->orderBy('s.idSuiviTicket','DESC')
                            ->setParameter('id_ticket', $id_ticket)
                            ->getQuery()->getResult();
    }


    /**
     * Add suiviTicket
     *
     * @param \AppBundle\Entity\FosUser $user
     * @param String $remarque
     *
     * @return Ticket
     */
    public function addSuiviTicket(Ticket $ticket,User $user,$remarque)
    {
        $suiviTicket = new SuiviTicket();
        $suiviTicket->setDate(new \DateTime());
        $suiviTicket->setIdStatut($this->getIdStatut());
        $suiviTicket->setIdUtilisateur($user);
        $suiviTicket->setIdTicket($ticket);
        $suiviTicket->setRemarque($remarque);

        $this->getEntityManager()->persist($suiviTicket);
        $this->getEntityManager()->flush($suiviTicket);

        return $this;
    }

}


