<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Ticket;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllByUtilisateur($id_utilisateur,$actif=true)
    {

        return $this->createQueryBuilder('t')
                            ->innerJoin('t.utilisateurs', 'u')
                            ->innerJoin('t.idStatut','s')
                            ->where('u.id = :id_user')
                            ->andWhere('s.clos = 0')
                            ->setParameter('id_user', $id_utilisateur)
                            ->getQuery()->getResult();
    }
}


